name: DocSet

on:
  push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
permissions:
  contents: write

  
jobs:
  generate-docs:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Doxyfile
        run: doxygen -g Doxyfile

      - name: Modify Doxyfile for Dash Docset
        run: |
          sed -i '' 's/GENERATE_TAGFILE *=.*/GENERATE_TAGFILE = spdlog.tag/' Doxyfile
          sed -i '' 's/GENERATE_DOCSET *=.*/GENERATE_DOCSET = YES/' Doxyfile
          sed -i '' 's/DOCSET_FEEDNAME *=.*/DOCSET_FEEDNAME = "spdlog"/' Doxyfile
          sed -i '' 's/DOCSET_BUNDLE_ID *=.*/DOCSET_BUNDLE_ID = "com.ownuse.spdlog"/' Doxyfile
          sed -i '' 's|OUTPUT_DIRECTORY *=.*|OUTPUT_DIRECTORY = ./docs|' Doxyfile
          sed -i '' 's|INPUT *=.*|INPUT = include src|' Doxyfile
          sed -i '' 's/RECURSIVE *=.*/RECURSIVE = YES/' Doxyfile
          sed -i '' 's/GENERATE_TREEVIEW *=.*/GENERATE_TREEVIEW = YES/' Doxyfile
          sed -i '' 's/SEARCHENGINE *=.*/SEARCHENGINE = YES/' Doxyfile
          sed -i '' 's/DISABLE_INDEX *=.*/DISABLE_INDEX = YES/' Doxyfile

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: List Output Directory
        run: ls -R ./docs

      - name: Print current Directory after your makes docs
        run: pwd
        

      - name: Print current Directory
        run: pwd
      - name: List Output Directory
        run: ls -R ./docs

      - name: Upload Documentation as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: ./docs/html
